# Generated by Django 4.2.13 on 2024-06-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jquery_ajax_app', '0002_post_date_posted_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
