# Generated by Django 4.2.13 on 2024-06-15 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jquery_ajax_app', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
